# Generated by Django 5.1.7 on 2025-05-10 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Actuator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
                ('actuator_type', models.CharField(choices=[('binario', 'Binario'), ('texto', 'Texto')], max_length=16)),
            ],
        ),
    ]
