# Generated by Django 5.1.7 on 2025-05-11 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0002_actuator'),
    ]

    operations = [
        migrations.AddField(
            model_name='actuator',
            name='value_boolean',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='actuator',
            name='value_text',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
