FROM python:3.10-slim

WORKDIR /app

# Instalar dependencias de compilación para PostgreSQL
RUN apt-get update && \
    apt-get install -y gcc libpq-dev && \
    pip install --upgrade pip

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copiamos el proyecto y scripts
COPY . .

# Copiamos y damos permisos al script de entrada
COPY entrypoint.sh /app/entrypoint.sh
RUN chmod +x /app/entrypoint.sh

ENV DJANGO_SETTINGS_MODULE=iot_ucr.settings.dev \
    PYTHONUNBUFFERED=1

ENTRYPOINT ["/app/entrypoint.sh"]
